/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import useAppStore from "../stores/useAppStore";
import { useFrame } from "@react-three/fiber";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/JordanOne.glb");
  const AppStore = useAppStore();

  useFrame(() => {
    if (AppStore.scene === 1) {
      group.current.rotation.y = group.current.rotation.y + 0.001;
    }
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.08}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              geometry={nodes.shoe_shoe_0.geometry}
              material={materials.shoe}
              material-color={AppStore.shoeColor}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              geometry={nodes.shoelace_shoelace_0.geometry}
              material={materials.shoelace}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/JordanOne.glb");
