/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/modelHome3.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-8.11, -10.55, -2]}>
          <mesh geometry={nodes.Mesh_0.geometry} material={materials.R0010524objmtl} />
          <mesh geometry={nodes.Mesh_1.geometry} material={materials.R0010525objmtl} />
          <mesh geometry={nodes.Mesh_10.geometry} material={materials.R0010536objmtl} />
          <mesh geometry={nodes.Mesh_11.geometry} material={materials.R0010537objmtl} />
          <mesh geometry={nodes.Mesh_12.geometry} material={materials.R0010538objmtl} />
          <mesh geometry={nodes.Mesh_13.geometry} material={materials.R0010539objmtl} />
          <mesh geometry={nodes.Mesh_14.geometry} material={materials.R0010540objmtl} />
          <mesh geometry={nodes.Mesh_15.geometry} material={materials.R0010541objmtl} />
          <mesh geometry={nodes.Mesh_16.geometry} material={materials.R0010542objmtl} />
          <mesh geometry={nodes.Mesh_17.geometry} material={materials.R0010543objmtl} />
          <mesh geometry={nodes.Mesh_18.geometry} material={materials.R0010544objmtl} />
          <mesh geometry={nodes.Mesh_19.geometry} material={materials.R0010545objmtl} />
          <mesh geometry={nodes.Mesh_2.geometry} material={materials.R0010526objmtl} />
          <mesh geometry={nodes.Mesh_20.geometry} material={materials.R0010546objmtl} />
          <mesh geometry={nodes.Mesh_21.geometry} material={materials.R0010547objmtl} />
          <mesh geometry={nodes.Mesh_3.geometry} material={materials.R0010527Bobjmtl} />
          <mesh geometry={nodes.Mesh_4.geometry} material={materials.R0010527objmtl} />
          <mesh geometry={nodes.Mesh_5.geometry} material={materials.R0010528objmtl} />
          <mesh geometry={nodes.Mesh_6.geometry} material={materials.R0010529objmtl} />
          <mesh geometry={nodes.Mesh_7.geometry} material={materials.R0010530objmtl} />
          <mesh geometry={nodes.Mesh_8.geometry} material={materials.R0010531objmtl} />
          <mesh geometry={nodes.Mesh_9.geometry} material={materials.R0010535objmtl} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/modelHome3.glb')
