/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/shoppingCart.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={3.86}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Mesh_0.geometry} material={materials.material} />
          <mesh geometry={nodes.Mesh_1.geometry} material={materials.Griff} />
          <mesh geometry={nodes.Mesh_2.geometry} material={materials.Chrome} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/shoppingCart.glb')
