/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/tourHouse2.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.38}>
        <mesh geometry={nodes.Mesh_0.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Mesh_1.geometry} material={materials['Material.014']} />
        <mesh geometry={nodes.Mesh_10.geometry} material={materials.foof} />
        <mesh geometry={nodes.Mesh_2.geometry} material={materials.black_stuff} />
        <mesh geometry={nodes.Mesh_3.geometry} material={materials.door1} />
        <mesh geometry={nodes.Mesh_4.geometry} material={materials.door2} />
        <mesh geometry={nodes.Mesh_5.geometry} material={materials.panesl} />
        <mesh geometry={nodes.Mesh_6.geometry} material={materials.slats} />
        <mesh geometry={nodes.Mesh_7.geometry} material={materials.slats_wood} />
        <mesh geometry={nodes.Mesh_8.geometry} material={materials.window} />
        <mesh geometry={nodes.Mesh_9.geometry} material={materials.woodfloor} />
      </group>
    </group>
  )
}

useGLTF.preload('/tourHouse2.glb')
