/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/youtubeLogo.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={[1.24, 2.03, 0.62]}>
            <group position={[148.38, -48.83, 0]}>
              <mesh geometry={nodes['Youtube_Logo_01_-_Default_0'].geometry} material={materials['01_-_Default']} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/youtubeLogo.glb')
